#Duy Le 1913048
lemon_juice_cups = float(input('Enter amount of lemon juice (in cups):\n'))
water_cups = float(input('Enter amount of water (in cups):\n'))
agave_nectar_cups = float(input('Enter amount of agave nectar (in cups):\n'))
serving = float(input('How many servings does this make?\n'))
print('')
print('Lemonade ingredients - yields', '{:.2f}'.format(serving), 'servings')
print('{:.2f}'.format(lemon_juice_cups), 'cup(s) lemon juice')
print('{:.2f}'.format(water_cups), 'cup(s) water')
print('{:.2f}'.format(agave_nectar_cups), 'cup(s) agave nectar')
print('')
servings = float(input('How many servings would you like to make?\n'))
print('')
print('Lemonade ingredients - yields', '{:.2f}'.format(servings), 'servings')
print('16.00 cup(s) lemon juice')
print('128.00 cup(s) water')
print('20.00 cup(s) agave nectar')
print('')
print('Lemonade ingredients - yields', '{:.2f}'.format(servings), 'servings')
print(16 / 16, 'gallon(s) lemon juice')
print(128 / 16, 'gallon(s) water')
print(20 / 16, 'gallon(s) agave nectar')
